version: "3"
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでOK
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: mysql
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test